# -*- coding: utf-8 -*

# Form implementation generated from reading ui file '/Users/matt/Documents/Fall2014/Research Stuff/Cardiac Output Python Project/UIstuff/UIv3.ui'
#
# Created: Sun Apr  5 23:53:58 2015
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(889, 608)
        self.commandLinkButton = QtGui.QCommandLinkButton(Form)
        self.commandLinkButton.setGeometry(QtCore.QRect(230, 290, 81, 41))
        self.commandLinkButton.setObjectName(_fromUtf8("commandLinkButton"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(120, 20, 81, 241))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lineEdit_1 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_1.setObjectName(_fromUtf8("lineEdit_1"))
        self.verticalLayout_3.addWidget(self.lineEdit_1)
        self.lineEdit_2 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.verticalLayout_3.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.verticalLayout_3.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.verticalLayout_3.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.verticalLayout_3.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.verticalLayout_3.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.verticalLayout_3.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.verticalLayout_3.addWidget(self.lineEdit_9)
        self.lineEdit_10 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.verticalLayout_3.addWidget(self.lineEdit_10)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 30, 56, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(229, 19, 81, 241))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lineEdit_12 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.verticalLayout.addWidget(self.lineEdit_12)
        self.lineEdit_11 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.verticalLayout.addWidget(self.lineEdit_11)
        self.lineEdit_13 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.verticalLayout.addWidget(self.lineEdit_13)
        self.lineEdit_14 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.verticalLayout.addWidget(self.lineEdit_14)
        self.lineEdit_15 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.verticalLayout.addWidget(self.lineEdit_15)
        self.lineEdit_16 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.verticalLayout.addWidget(self.lineEdit_16)
        self.lineEdit_17 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.verticalLayout.addWidget(self.lineEdit_17)
        self.lineEdit_18 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.verticalLayout.addWidget(self.lineEdit_18)
        self.lineEdit_19 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.verticalLayout.addWidget(self.lineEdit_19)
        self.lineEdit_20 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.verticalLayout.addWidget(self.lineEdit_20)
        self.gridLayoutWidget = QtGui.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 280, 131, 51))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_21 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.gridLayout.addWidget(self.lineEdit_21, 0, 1, 1, 1)
        self.lineEdit_22 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.gridLayout.addWidget(self.lineEdit_22, 1, 1, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(70, 360, 241, 121))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.lineEdit_24 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.gridLayout_2.addWidget(self.lineEdit_24, 0, 1, 1, 1)
        self.lineEdit_23 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.gridLayout_2.addWidget(self.lineEdit_23, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.lineEdit_25 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.gridLayout_2.addWidget(self.lineEdit_25, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_26 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.gridLayout_2.addWidget(self.lineEdit_26, 1, 3, 1, 1)
        self.lineEdit_27 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.gridLayout_2.addWidget(self.lineEdit_27, 0, 3, 1, 1)
        self.lineEdit_28 = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.gridLayout_2.addWidget(self.lineEdit_28, 2, 3, 1, 1)
        self.widget = matplotlibWidget(Form)
        self.widget.setGeometry(QtCore.QRect(339, 29, 511, 451))
        self.widget.setObjectName(_fromUtf8("widget"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLinkButton.setText(QtGui.QApplication.translate("Form", "submit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Data:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Nothing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "AUC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "R^2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "CO", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidgetFile import matplotlibWidget
